name: Set Content-Type

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Content-Type
        run: echo 'Content-Type: application/json' > $GITHUB_WORKSPACE/media.json
